export const galleryData = [
  {
    category: "fastlane",
    images: [
      "/images/gallery/fastlane1.jpg",
      "/images/gallery/fastlane2.jpg",
      "/images/gallery/fastlane3.jpg",
      "/images/gallery/fastlane4.jpg",
      "/images/gallery/fastlane5.jpg",
      "/images/gallery/fastlane6.jpg",
      "/images/gallery/fastlane7.jpg",
    ],
  },
  {
    category: "plunge",
    images: [
      "/images/gallery/plunge1.jpg",
      "/images/gallery/plunge2.jpg",
      "/images/gallery/plunge3.jpg",
      "/images/gallery/plunge4.jpg",
      "/images/gallery/plunge5.jpg",
      "/images/gallery/plunge6.jpg",
      "/images/gallery/plunge7.jpg",
      "/images/gallery/plunge8.jpg",
      "/images/gallery/plunge9.jpg",
    ],
  },
  {
    category: "sanctuary",
    images: [
      "/images/gallery/sanctuary1.jpg",
      "/images/gallery/sanctuary2.jpg",
      "/images/gallery/sanctuary3.jpg",
      "/images/gallery/sanctuary4.jpg",
      "/images/gallery/sanctuary5.jpg",
      "/images/gallery/sanctuary6.jpg",
      "/images/gallery/sanctuary7.jpg",
      "/images/gallery/sanctuary8.jpg",
    ],
  },
  {
    category: "vogue",
    images: [
      "/images/gallery/vogue1.jpg",
      "/images/gallery/vogue2.jpg",
      "/images/gallery/vogue3.jpg",
      "/images/gallery/vogue4.jpeg",
      "/images/gallery/vogue5.jpeg",
      "/images/gallery/vogue6.jpg",
      "/images/gallery/vogue7.jpg",
      "/images/gallery/vogue8.jpg",
    ],
  },
  {
    category: "x-trainer",
    images: [
      "/images/gallery/xtrainer1.jpg",
      "/images/gallery/xtrainer2.jpg",
      "/images/gallery/xtrainer3.jpg",
      "/images/gallery/xtrainer4.jpg",
      "/images/gallery/xtrainer5.jpg",
      "/images/gallery/xtrainer6.jpg",
      "/images/gallery/xtrainer7.jpg",
      "/images/gallery/xtrainer8.jpg",
      "/images/gallery/xtrainer9.jpg",
      "/images/gallery/xtrainer10.jpg",
      "/images/gallery/xtrainer11.jpg",
      "/images/gallery/xtrainer12.jpg",
      "/images/gallery/xtrainer13.jpg",
      "/images/gallery/xtrainer14.jpg",
      "/images/gallery/xtrainer15.jpg",
      "/images/gallery/xtrainer16.jpg",
      "/images/gallery/xtrainer17.jpg",
    ],
  },
  {
    category: "other",
    images: [
      "/images/gallery/other1.jpg",
      "/images/gallery/other2.jpg",
      "/images/gallery/other3.jpg",
      "/images/gallery/other4.jpg",
      "/images/gallery/other5.jpg",
      "/images/gallery/other6.jpg",
    ],
  },
];
