export const pools = [
  {
    name: "Family Pools",
    slug: "family-pools",
    body: "Chill out when others burn out! We can show you how to create your dream family pool. Our knowledge, innovation and commitment to excellence will mean that your pool will be loved and enjoyed by everyone in the family for years to come.",
    img: "/images/family-pool.png",
    info: [
      {
        model: "X-Trainer 11.7",
        category: "x-trainer",
        length: "11.74m",
        width: "4.2m",
        shallow_end: "1.09m",
        deep_end: "1.93m",
        img: "/images/pool/x-trainer-11.7.png",
      },
      {
        model: "X-Trainer 10.2",
        category: "x-trainer",
        length: "10.2m",
        width: "4.2m",
        shallow_end: "1.09m",
        deep_end: "1.93m",
        img: "/images/pool/x-trainer-10.2.png",
      },
      {
        model: "X-Trainer 9.4",
        category: "x-trainer",
        length: "9.4m",
        width: "4.2m",
        shallow_end: "1.07m",
        deep_end: "1.85m",
        img: "/images/pool/x-trainer-9.4.png",
      },
      {
        model: "X-Trainer 8.2",
        category: "x-trainer",
        length: "8.2m",
        width: "4.2m",
        shallow_end: "1.09m",
        deep_end: "1.75m",
        img: "/images/pool/x-trainer-8.2.png",
      },
      {
        model: "X-Trainer 8.2 Slim",
        category: "x-trainer",
        length: "8.2m",
        width: "3.0m",
        shallow_end: "1.09m",
        deep_end: "1.75m",
        img: "/images/pool/x-trainer-8.2slim.png",
      },
      {
        model: "X-Trainer 7.2",
        category: "x-trainer",
        length: "7.2m",
        width: "3.7m",
        shallow_end: "1.09m",
        deep_end: "1.68m",
        img: "/images/pool/x-trainer-7.2.png",
      },
      {
        model: "X-Trainer 7.15 Slim",
        category: "x-trainer",
        length: "7.15m",
        width: "3.0m",
        shallow_end: "1.09m",
        deep_end: "1.68m",
        img: "/images/pool/x-trainer-7.15sl.png",
      },
      {
        model: "Sanctuary 10.6",
        category: "sanctuary",
        length: "10.6m",
        width: "4.2m",
        shallow_end: "1.18m",
        deep_end: "1.97m",
        img: "/images/pool/sanctuary-10.6.png",
      },
      {
        model: "Sanctuary 9.4",
        category: "sanctuary",
        length: "9.4m",
        width: "4.2m",
        shallow_end: "1.18m",
        deep_end: "1.97m",
        img: "/images/pool/sanctuary-9.4.png",
      },
      {
        model: "Sanctuary 8.2",
        category: "sanctuary",
        length: "8.2m",
        width: "4.2m",
        shallow_end: "1.18m",
        deep_end: "1.85m",
        img: "/images/pool/sanctuary-8.2.png",
      },
      {
        model: "Sanctuary 7.0",
        category: "sanctuary",
        length: "7.0m",
        width: "4.2m",
        shallow_end: "1.18m",
        deep_end: "1.74m",
        img: "/images/pool/sanctuary-7.0.png",
      },
      {
        model: "Sanctuary 6.0",
        category: "sanctuary",
        length: "6.0m",
        width: "4.2m",
        shallow_end: "1.18m",
        deep_end: "1.65m",
        img: "/images/pool/sanctuary-6.0.png",
      },
      {
        model: "Sanctuary 6.0 Narrow",
        category: "sanctuary",
        length: "6.0m",
        width: "3.4m",
        shallow_end: "1.18m",
        deep_end: "1.65m",
        img: "/images/pool/sanctuary-6.0narrow.png",
      },
      {
        model: "Vogue 10.2",
        category: "vogue",
        length: "10.2m",
        width: "4.2m",
        shallow_end: "1.09m",
        deep_end: "1.93m",
        img: "/images/pool/vogue-10.2.png",
      },
      {
        model: "Vogue 9.4",
        category: "vogue",
        length: "9.4m",
        width: "4.2m",
        shallow_end: "1.09m",
        deep_end: "1.86m",
        img: "/images/pool/vogue-9.4.png",
      },
      {
        model: "Vogue 8.2",
        category: "vogue",
        length: "8.2m",
        width: "4.2m",
        shallow_end: "1.09m",
        deep_end: "1.75m",
        img: "/images/pool/vogue-8.2.png",
      },
      {
        model: "Vogue 7.15",
        category: "vogue",
        length: "7.15m",
        width: "3.6m",
        shallow_end: "1.09m",
        deep_end: "1.68m",
        img: "/images/pool/vogue-7.15.png",
      },
      {
        model: "Vogue 7.15 Slim",
        category: "vogue",
        length: "7.15m",
        width: "3.0m",
        shallow_end: "1.09m",
        deep_end: "1.68m",
        img: "/images/pool/vogue-7.15SL.png",
      },
    ],
  },
  {
    name: "Lap Pools",
    slug: "lap-pools",
    body: "Lap pools are a popular addition to many Aussie backyards, providing homeowners with a convenient and private place to exercise and relax. Lap pools can also add value to a property and enhance the overall aesthetic appeal of a home.",
    img: "/images/lap-pool.png",
    info: [
      {
        model: "Fastlane 10.3",
        category: "fastlane",
        length: "10.3m",
        width: "2.78m",
        shallow_end: "1.46m",
        deep_end: "1.46m",
        img: "/images/pool/fastlane-10.3.png",
      },
      {
        model: "Custom Length Fastlane",
        category: "fastlane",
        length: "Up to 30m",
        width: "2.78m",
        shallow_end: "1.46m",
        deep_end: "1.46m",
        img: "/images/pool/custom-length-fastlane.png",
      },
      {
        model: "Optional External Steps",
        category: "",
        length: "3.2m",
        width: "1.2m",
        shallow_end: "",
        deep_end: "",
        img: "/images/pool/optional-external-steps.png",
      },
    ],
  },
  {
    name: "Plunge Pools",
    slug: "plunge-pools",
    body: "Plunge pools are a growing trend in our backyards, offering a refreshing and stylish addition to outdoor living spaces. With their small size and deep water, these pools are perfect for hot summer days and provide a space to cool off and relax with family and friends",
    img: "/images/plunge-pool.png",
    info: [
      {
        model: "X-Trainer 5.8",
        category: "x-trainer",
        length: "5.8m",
        width: "3.0m",
        shallow_end: "1.11m",
        deep_end: "1.52m",
        img: "/images/pool/x-trainer-5.8.png",
      },
      {
        model: "X-Trainer 5.8 Slim",
        category: "x-trainer",
        length: "5.8m",
        width: "2.7m",
        shallow_end: "1.11m",
        deep_end: "1.52m",
        img: "/images/pool/x-trainer-5.8sl.png",
      },
      {
        model: "Plunge 5.0",
        category: "plunge",
        length: "5.0m",
        width: "3.4m",
        shallow_end: "1.42m",
        deep_end: "1.7m",
        img: "/images/pool/plunge-5.0.png",
      },
      {
        model: "Plunge 3.8",
        category: "plunge",
        length: "3.8m",
        width: "2.13m",
        shallow_end: "1.2m",
        deep_end: "1.2m",
        img: "/images/pool/plunge-3.8.png",
      },
      {
        model: "Plunge 2.8",
        category: "plunge",
        length: "2.8m",
        width: "2.13m",
        shallow_end: "1.2m",
        deep_end: "1.2m",
        img: "/images/pool/plunge-2.8.png",
      },
      {
        model: "Sanctuary 6.0",
        category: "sanctuary",
        length: "6.0m",
        width: "4.2m",
        shallow_end: "1.18m",
        deep_end: "1.65m",
        img: "/images/pool/sanctuary-6.0.png",
      },
      {
        model: "Sanctuary 6.0 Narrow",
        category: "sanctuary",
        length: "6.0m",
        width: "3.4m",
        shallow_end: "1.18m",
        deep_end: "1.65m",
        img: "/images/pool/sanctuary-6.0narrow.png",
      },
      {
        model: "Sanctuary 4.8",
        category: "sanctuary",
        length: "4.8m",
        width: "3.4m",
        shallow_end: "1.18m",
        deep_end: "1.54m",
        img: "/images/pool/sanctuary-4.8.png",
      },
      {
        model: "4 Plunge",
        category: "plunge",
        length: "4.37m",
        width: "2.22m",
        shallow_end: "1.24m",
        deep_end: "1.24m",
        img: "/images/pool/4-plunge.png",
      },
      {
        model: "3 Plunge",
        category: "plunge",
        length: "3.37m",
        width: "2.22m",
        shallow_end: "1.24m",
        deep_end: "1.24m",
        img: "/images/pool/3-plunge.png",
      },
      {
        model: "Relax 6.3",
        category: "",
        length: "6.72m",
        width: "2.33m",
        shallow_end: "1.39m",
        deep_end: "1.39m",
        img: "/images/pool/relax-6.3.png",
      },
      {
        model: "Relax 5.2",
        category: "",
        length: "5.70m",
        width: "2.33m",
        shallow_end: "1.39m",
        deep_end: "1.39m",
        img: "/images/pool/relax-5.2.png",
      },
      {
        model: "Relax 4.0",
        category: "",
        length: "4.47m",
        width: "2.33m",
        shallow_end: "1.39m",
        deep_end: "1.39m",
        img: "/images/pool/relax-4.0.png",
      },
      {
        model: "Refresh Max",
        category: "",
        length: "6.60m",
        width: "3.05m",
        shallow_end: "1.49m",
        deep_end: "1.49m",
        img: "/images/pool/refresh-max.png",
      },
    ],
  },
  {
    name: "Wellness Pools",
    slug: "wellness-pools",
    body: "Featuring a dual hot and cold contrast therapy pool that accommodates two people, this pool is designed to offer a range of potential benefits including improved circulation, pain relief, muscle recovery, and stress relief.",
    img: "/images/wellness-pool.png",
    info: [
      {
        model: "Fastlane 10.3",
        category: "fastlane",
        length: "10.3m",
        width: "2.78m",
        shallow_end: "1.46m",
        deep_end: "1.46m",
        img: "/images/pool/fastlane-10.3.png",
      },
      {
        model: "Custom Length Fastlane",
        category: "fastlane",
        length: "Up to 30m",
        width: "2.78m",
        shallow_end: "1.46m",
        deep_end: "1.46m",
        img: "/images/pool/custom-length-fastlane.png",
      },
      {
        model: "X-Trainer Spa",
        category: "x-trainer",
        length: "2.8m",
        width: "1.8m",
        shallow_end: "1.1m",
        deep_end: "1.1m",
        img: "/images/pool/x-trainer-spa.png",
      },
      {
        model: "Immersion Therapy Pod",
        category: "",
        length: "1.93m",
        width: "0.9m",
        shallow_end: "0.8m",
        deep_end: "0.8m",
        img: "/images/pool/immersion-therapy-pod.png",
      },
    ],
  },
];
