import { Inter, Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`bg-gray-100 ${manrope.className}`}>{children}</body>
    </html>
  );
}
