import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Header from "@/components/header";

const manrope = Manrope({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-100 ${manrope.className}`}
        suppressHydrationWarning={true}
      >
        <div className="relative z-50">
          <div className="absolute">
            <Header />
          </div>
        </div>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
